config/routes.rb
Rails.application.routes.draw do

  #root 'application#bye'

  #root 'greetings#index'

  root 'animals#index'

  resources :animals
  resources :cats

end

app/models/animal.rb
class Animal < ApplicationRecord
  validates :name, presence: true

  def age
    if birthdate
      today = Date.today
      (today.mjd - birthdate.mjd).to_i
    end
  end
end

app/models/animal_type.rb
class AnimalType

  attr_accessor :type

  def initialize(type)
    @type = type
  end

  def to_s
    type
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
# == Schema Information
#
# Table name: birds
#
#  id         :integer          not null, primary key
#  name       :string
#  prename    :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bird < ApplicationRecord
  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ApplicationRecord
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id         :integer          not null, primary key
#  name       :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pre_name   :string
#

class Cat < ApplicationRecord

  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id         :integer          not null, primary key
#  name       :string
#  pre_name   :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Dog < ApplicationRecord

  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
  
end

app/models/elefant.rb
# == Schema Information
#
# Table name: elefants
#
#  id         :integer          not null, primary key
#  name       :string
#  prename    :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Elefant < ApplicationRecord

  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/models/horse.rb
# == Schema Information
#
# Table name: horses
#
#  id         :integer          not null, primary key
#  name       :string
#  pre_name   :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Horse < ApplicationRecord
  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/models/lion.rb
# == Schema Information
#
# Table name: lions
#
#  id         :integer          not null, primary key
#  name       :string
#  pre_name   :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Lion < ApplicationRecord

  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/models/snake.rb
# == Schema Information
#
# Table name: snakes
#
#  id         :integer          not null, primary key
#  name       :string
#  prename    :string
#  birthdate  :date
#  info       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Snake < ApplicationRecord

  validates :name, presence: true

  def age
    today = Date.today
    (today.mjd - birthdate.mjd).to_i
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  def new
    @bird = Bird.new
  end

  def index
    @birds = Bird.all
  end

  def create
    @bird = Bird.new(bird_params)

    if @bird.save
      redirect_to action: "index"
    else
      redirect_to new_bird_path, flash: {error: "Bisch eigentli blöd, e Vogu ohni Name????"}
    end
  end

  def show
    @bird = Bird.find(params[:id])
  end

  def edit
    @bird = Bird.find(params[:id])
  end

  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy
    redirect_to action: "index"
  end

  def update
    @bird = Bird.find(params[:id])
    @bird.update_attributes(bird_params)
    redirect_to action: "index"
  end

  private

  def bird_params
    params.require(:bird).permit(:name, :prename, :birthdate, :info)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def new
    @cat = Cat.new
  end

  def index
    @cats = Cat.all
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to action: "index"
    else
      redirect_to new_cat_path, flash: {error: "Bisch eigentli blöd, e Chatz ohni Name????"}
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to action: "index"
  end

  def update
    @cat = Cat.find(params[:id])  
    @cat.update_attributes(cat_params)
    redirect_to action: "index"
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :pre_name, :birthdate, :info)
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def new
    @dog = Dog.new
  end

  def index
    @dogs = Dog.all
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to action: "index"
    else
      redirect_to new_dog_path, flash: {error: "Bisch eigentli blöd, e Hund ohni Name????"}
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to action: "index"
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update_attributes(dog_params)
    redirect_to action: "index"
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :pre_name, :birthdate, :info)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dog_helper.rb
module DogHelper
end

app/helpers/elefants_helper.rb
module ElefantsHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/lions_helper.rb
module LionsHelper
end

app/helpers/snake_helper.rb
module SnakeHelper
end

app/views/cats/edit.erb
<div class="row">
  <div class="col-9">
    <span class="align-bottom">
      <h1><%= "Edit: #{@cat.name}" %></h1>
    </span>
  </div>
  <div class="col-3 text-right">
    <span class="align-bottom text-right">
      <%= link_to "Zurück", cats_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<%= form_for @cat, :url => { :action => "update" } do |f| %>

  <table class="table cats-table">
    <tr>
      <td>
        <b>
          <%= f.label :name %>
        </b>
      </td>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :pre_name%>
        </b>
      </td>
      <td>
        <%= f.text_field :pre_name, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :birthdate %>
        </b>
      </td>
      <td>
        <%= f.date_field :birthdate, class: "form-control"%>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :info %>
        </b>
      </td>
      <td>
        <%= text_area(:cat, :info , cols: 20, rows: 40, class: "form-control")%>
      </td>
    </tr>
  </table>

  <div class="row">
    <div class="col-12 text-right">
        <%= f.submit "Speichern", class: "btn btn-primary"%>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-right">
        <br>
    </div>
  </div>

<% end %>

app/views/cats/index.erb
<div class="row">
  <div class="col-10">
    <span class="align-bottom">
      <h1>Alle Kazen</h1>
    </span>
  </div>
  <div class="col-2">
    <span class="align-bottom">
      <%= link_to "Neue Katze", new_cat_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <table class="table table-striped">
      <thead class="bg-primary text-white font-weight-bold">
        <tr>
          <td>
            Vorname
          </td>
          <td>
            Name
          </td>
          <td>
            Alter
          </td>
          <td>
            Info
          </td>
          <td class="text-right">
            Aktionen
          </td>
        </tr>
      </thad>
      <tbody>
        <% @cats.each do |cat| %>
          <tr>
            <td>
              <%= cat.pre_name %>
            </td>
            <td>
              <%= cat.name %>
            </td>
            <td>
              <%= cat.age %>
            </td>
            <td>
              <%= cat.info %>
            </td>
            <td class="text-right">
              <div class="row">
                <div class="col">
                  <%= link_to "Delete", cat_path(cat), method: :delete, data: {confirm: "Bisch sicher ?"}, class: "btn btn-danger" %>
                  <%= link_to "Edit", edit_cat_path(cat), class: "btn btn-primary" %>
                  <%= link_to "View", cat_path(cat), class: "btn btn-primary" %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cats/new.erb
<h1>Neue Katze erfassen</h1>

<br>

<%= form_for @cat do |f| %>

  <table>
    <tr>
      <td>
        <%= f.label :name %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :pre_name %>
      </td>
      <td>
        <%= f.text_field :pre_name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :birthdate %>
      </td>
      <td>
        <%= f.date_field :birthdate%>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :info %>
      </td>
      <td>
        <%= text_area(:cat, :info , cols: 20, rows: 40) %>
      </td>
    </tr>
  </table>

  <%= f.submit %>

<% end %>

app/views/cats/show.erb
<div class="row">
  <div class="col-9">
    <span class="align-bottom">
      <h1><%= "#{@cat.name}" %></h1>
    </span>
  </div>
  <div class="col-3">
    <span class="align-bottom text-right">
      <%= link_to "Edit", edit_cat_path(@cat), class: "btn btn-primary" %>
      <%= link_to "Zurück", cats_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <table class="table cats-table">
      <tr>
        <td>
          <b>
            Vorname
          </b>
        </td>
        <td>
          <%= @cat.pre_name %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Name
          </b>
        </td>
        <td>
          <%= @cat.name %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Geburtsdatum
          </b>
        </td>
        <td>
          <%= @cat.birthdate %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Info
          </b>
        </td>
        <td>
          <%= @cat.info %>
        </td>
      </tr>

    </table>
  </div>
</div>

app/views/dogs/edit.erb
<div class="row">
  <div class="col-9">
    <span class="align-bottom">
      <h1><%= "Edit: #{@dog.name}" %></h1>
    </span>
  </div>
  <div class="col-3 text-right">
    <span class="align-bottom text-right">
      <%= link_to "Zurück", dogs_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<%= form_for @dog, :url => { :action => "update" } do |f| %>

  <table class="table dogs-table">
    <tr>
      <td>
        <b>
          <%= f.label :name %>
        </b>
      </td>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :pre_name%>
        </b>
      </td>
      <td>
        <%= f.text_field :pre_name, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :birthdate %>
        </b>
      </td>
      <td>
        <%= f.date_field :birthdate, class: "form-control"%>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <%= f.label :info %>
        </b>
      </td>
      <td>
        <%= text_area(:dog, :info , cols: 20, rows: 40, class: "form-control")%>
      </td>
    </tr>
  </table>

  <div class="row">
    <div class="col-12 text-right">
        <%= f.submit "Speichern", class: "btn btn-primary"%>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-right">
        <br>
    </div>
  </div>

<% end %>

app/views/dogs/index.erb
<div class="row">
  <div class="col-10">
    <span class="align-bottom">
      <h1>Alle Hunde</h1>
    </span>
  </div>
  <div class="col-2">
    <span class="align-bottom">
      <%= link_to "Neuer Hund", new_dog_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <table class="table table-striped">
      <thead class="bg-primary text-white font-weight-bold">
        <tr>
          <td>
            Vorname
          </td>
          <td>
            Name
          </td>
          <td>
            Alter
          </td>
          <td>
            Info
          </td>
          <td class="text-right">
            Aktionen
          </td>
        </tr>
      </thad>
      <tbody>
        <% @dogs.each do |dog| %>
          <tr>
            <td>
              <%= dog.pre_name %>
            </td>
            <td>
              <%= dog.name %>
            </td>
            <td>
              <%= dog.age %>
            </td>
            <td>
              <%= dog.info %>
            </td>
            <td class="text-right">
              <div class="row">
                <div class="col">
                  <%= link_to "Delete", dog_path(dog), method: :delete, data: {confirm: "Bisch sicher ?"}, class: "btn btn-danger" %>
                  <%= link_to "Edit", edit_dog_path(dog), class: "btn btn-primary" %>
                  <%= link_to "View", dog_path(dog), class: "btn btn-primary" %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dogs/new.erb
<h1>Neue Hunde erfassen</h1>

<br>

<%= form_for @dog do |f| %>

  <table>
    <tr>
      <td>
        <%= f.label :name %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :pre_name %>
      </td>
      <td>
        <%= f.text_field :pre_name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :birthdate %>
      </td>
      <td>
        <%= f.date_field :birthdate%>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :info %>
      </td>
      <td>
        <%= text_area(:dog, :info , cols: 20, rows: 20) %>
      </td>
    </tr>
  </table>

  <%= f.submit %>

<% end %>

app/views/dogs/show.erb
<div class="row">
  <div class="col-9">
    <span class="align-bottom">
      <h1><%= "#{@dog.name}" %></h1>
    </span>
  </div>
  <div class="col-3">
    <span class="align-bottom text-right">
      <%= link_to "Edit", edit_dog_path(@dog), class: "btn btn-primary" %>
      <%= link_to "Zurück", dogs_path, class: "btn btn-primary" %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <br/>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <table class="table dogs-table">
      <tr>
        <td>
          <b>
            Vorname
          </b>
        </td>
        <td>
          <%= @dog.pre_name %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Name
          </b>
        </td>
        <td>
          <%= @dog.name %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Geburtsdatum
          </b>
        </td>
        <td>
          <%= @dog.birthdate %>
        </td>
      </tr>
      <tr>
        <td>
          <b>
            Info
          </b>
        </td>
        <td>
          <%= @dog.info %>
        </td>
      </tr>

    </table>
  </div>
</div>